##########################################
##### DPMES
##########################################
server:
  port: 8090
  tomcat:
    accept-count: 1000
    max-connections: 1000
    max-threads: 4000
    min-spare-threads: 1000

spring:
  application:
    name: meta
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: oracle
    properties:
      hibernate:
        jdbc:
          fetch_size: 100
          batch_size: 30
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true      
        enable_lazy_load_no_trans: true
        
#        hikari:
#          dataSource:
#            cachePrepStmts: true
#            prepStmtCacheSize: 250
#            prepStmtCacheSqlLimit: 2048
#            useServerPrepStmts: true
#        default_batch_fetch_size: 50
        
#        dialect: org.hibernate.dialect.HSQLDialect
#        dialect: org.hibernate.dialect.OracleDialect
        show_sql: false
        meta_sql: false
    hibernate:
      ddl-auto: none
    show-sql: false 

  datasource:
    jdbc-url: jdbc:oracle:thin:@192.168.0.1:8080/DB1
    username: DB1
    password: db1
    driver-class-name: oracle.jdbc.OracleDriver

wony:
  datasource:
    jdbc-url: jdbc:oracle:thin:@192.168.0.1:8080:WONY
    username: WONY
    password: wony12
    driver-class-name: oracle.jdbc.OracleDriver
    

logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.mig.base: DEBUG
    org.hibernate.engine: ERROR
    org.hibernate.validator: ERROR
    org.hibernate.persister: ERROR
    org.hibernate.boot: ERROR
    org.hibernate.cfg: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.loader: ERROR
    org.hibernate.event: ERROR
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG
